### ISSUE TITLE
Compiling libmetis leads to problems

### ISSUE THREAD

**Issue by basnijholt** [conda-forge/suitesparse-feedstock#17]
After I updated `kwant` to `openblas 0.2.19|0.2.19.*`, installing `suitesparse` leads to `Segmentation fault (core dumped)` when importing `kwant`.

getting a backtrace from the coredump I see that the segfault happens here
`0x00007f6235a44934 in libmetis__CompressGraph () from /home/tinkerer/.conda/envs/anaconda/lib/libmetis.so`

this reproduces the problem:

```bash
conda create --yes --copy --name test6 python=3.5
source activate test6
conda install --yes -c conda-forge kwant=1.2.2
python -c 'import kwant'
conda install --yes -c conda-forge suitesparse
python -c 'import kwant'
```

It's probably because `suitesparse` has it's own `libmetis`, while there is a [metis-feedstock](https://github.com/conda-forge/metis-feedstock/)

**Comment by basnijholt** [comment]
I see that this point came up [before](https://github.com/conda-forge/suitesparse-feedstock/pull/3#issuecomment-223148283)

**Comment by jakirkham** [comment]
Work on this occurring in PR ( https://github.com/conda-forge/suitesparse-feedstock/pull/18 ).

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/conda-forge/suitesparse-feedstock/pull/18 ).
