### ISSUE TITLE
investigate setting install name

### ISSUE THREAD

**Issue by minrk** [conda-forge/suitesparse-feedstock#22]
on macOS, dylibs should have their install_name (set with `install_name_tool -id`) set to the name that should be used to load the library. At its *most* specific, this should be the ABI-compatible version (`*.4.dylib` or `*.4.5.dylib`). However, the libs from suitesparse appear to set their install_name to their *full* name (e.g. `libsuitesparseconfig.4.5.4.dylib`), indicating that every patch-level release can make ABI changes.

This means that all downstream packages have to pin their dependency on suitesparse to the patch-level, because any upgrade to suitesparse, even a compatible one, will result in an `image not found` error on the old location:

```
Library not loaded: @rpath/libsuitesparseconfig.4.5.3.dylib
  Referenced from: /Users/minrk/conda/envs/petsc/lib/libslepc.3.7.dylib
  Reason: image not found
```

(here slepc shows an example of how this can be done: libslepc's install_name is `libslepc.3.7.dylib`, even though the actual file is `libslepc.3.7.1.dylib`)

Setting the install_name to the general (version-less) path or the ABI-compatibility version would allow for upgrading suitesparse to a compatible version without needing to rebuild the downstream package.

This should probably be reported upstream to suitesparse itself, but it can be addressed in the conda package by running `install_name_tool -id ...` in build.sh after `make install`.

**Comment by jakirkham** [comment]
This definitely was an issue with 4.4.\*. However 4.5.\* and 5.\* have not had this issue.

ref: https://abi-laboratory.pro/tracker/timeline/suitesparse/

**Comment by minrk** [comment]
This is still an issue with 4.5.6.

Note that this issue is *not* about an ABI breakage. It's the opposite. The ABI is fine. It's the`install_name`, which causes linking to fail to find the file. If it found the file, it would load fine. It is compatible, it's just using the wrong filename, which makes it fail to be found, even though it's compatible.

Here's a quick test with a dummy test.c:

```c
int main(int argc, char const *argv[])
{
    return 0;
}
```

```bash
export PREFIX=/tmp/suite-env
conda create -y -p $PREFIX suitesparse=4.5.4
cc -L$PREFIX/lib -lsuitesparseconfig test.c -o test
./test # ok
conda install -y -p $PREFIX suitesparse=4.5.6
./test # fails
```

Running a program linked against 4.5.4 with 4.5.6 installed fails with:

```
dyld: Library not loaded: @rpath/libsuitesparseconfig.4.5.4.dylib
  Referenced from: /Users/minrk/dev/temp/./test
  Reason: image not found
Abort trap: 6
```

The install_name should not be the full libsuitesparseconfig.4.5.4.dylib, it should be libsuitesparseconfig.dylib (or .4.dylib). That's what #23 fixes.

**Comment by jakirkham** [comment]
Ah ok. Misread. Thanks for the clarification.
