### ISSUE TITLE
Investigate Windows builds

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/suitesparse-feedstock#4]
I have investigated Windows builds before and there were two takehomes:
- The Makefiles do not play well on Windows. I did not try Msys2, however, so that might actually help.
- BLAS on Windows is a huge pain.

Will investigate getting working Windows builds at some point in the future but I foresee it being painful, particularly if we haven't rectified OpenBLAS on Windows yet.

**Comment by jakirkham** [comment]
xref: https://github.com/conda-forge/openblas-feedstock/issues/2

**Comment by jakirkham** [comment]
A proposal for a Windows build exists in PR ( https://github.com/conda-forge/suitesparse-feedstock/pull/30 ).
