### ISSUE TITLE
unbundle libraries?

### ISSUE THREAD

**Issue by minrk** [conda-forge/suitesparse-feedstock#55]
suitesparse really is a "suite" of libraries. Until recently, most if not all of these were not available elsewhere, so packaging it as one thing makes the most sense.

With 5.4 (#54), however, suitesparse adds two new packages GraphBLAS and Mongoose, which are themselves individually packaged, versioned, and released on their own cadence, more frequent than the rest of SuiteSparse. GraphBLAS, in particular, constitutes ~90% of the build time of SuiteSparse 5.4, increasing build times from 7 minutes to over an hour. I probably wouldn't bother bringing this up, otherwise.

Choices:

- package GraphBLAS and/or Mongoose separately? (If no, no point in discussing the rest)
- should suitesparse package depend these packages? e.g. SuiteSparse 5.4 bundles GraphBLAS 2.2.2, but current GraphBLAS is 3.1.0. Is there a stability concern? If so, should the dependency pin the version exactly, or use a range?
- Should we go all the way and package the individual libraries as multiple outputs?

Issues:

- GraphBLAS has no links with the rest of SuiteSparse, so is easily separated (it's a bit weird that it's bundled, IMO, and possibly due mainly to being developed by the same group), but
- <del>Mongoose depends on SuiteSparseConfig. The Mongoose standalone repo includes a *copy* of SuiteSparseConfig, so we'd have to be careful to avoid a conflict with `libsuitesparseconfig.dylib`. This makes it hard for SuiteSparse to depend on Mongoose, because Mongoose depends on SuiteSparse. I think this is only really feasible if we explode this recipe into having multiple outputs. For suitesparseconfig, if nothing else.</del> mongoose appears to bundle a statically compiled suitesparseconfig, so there should be no dependency here.

**Comment by jayfurmanek** [comment]
I'd prefer if GraphBlas were done separately, if possible. Build time limits on the various CI vary, but I don't think I've seen any that allow up to 6 hour builds. It'd be nice to have all the other tools still available on all platforms.

**Comment by minrk** [comment]
Would you make it a dependency of suitesparse or fully separate?

**Comment by jayfurmanek** [comment]
My preference is that coded dependencies should be there for a real technical reason (ex: GraphBlas using some subset of suitesparse functions to complete its work), and if there is nothing that links them, then no deps get coded.

Maybe there are some other examples of packages with numerous independent submodules we can emulate.

**Comment by jayfurmanek** [comment]
Amazingly fast work @minrk !
